name: Snake2
dependencies:
  - python=3.5
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - pip
  - pip:
    - torch==1.4.0
    - pygame==1.9.3
    - GPyOpt==1.2.6
    - tensorflow==1.5.0
    - cmake
    - stable-baselines
